// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASIqFd0jFYo5Wwd8uVxF6q2xSCQFrvC90',
    appId: '1:318323347329:web:c5983776a1dfdd0ab66280',
    messagingSenderId: '318323347329',
    projectId: 'smsviewerapp-42d29',
    authDomain: 'smsviewerapp-42d29.firebaseapp.com',
    databaseURL: 'https://smsviewerapp-42d29-default-rtdb.firebaseio.com',
    storageBucket: 'smsviewerapp-42d29.firebasestorage.app',
    measurementId: 'G-90EWD20JQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbetqKg0TuR8bcrGe7iLhbTnAJcNR9ArM',
    appId: '1:318323347329:android:36e59f311fae05dcb66280',
    messagingSenderId: '318323347329',
    projectId: 'smsviewerapp-42d29',
    databaseURL: 'https://smsviewerapp-42d29-default-rtdb.firebaseio.com',
    storageBucket: 'smsviewerapp-42d29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn8bSPKhI30hssnoEJ4WL_b7kAsRocpxg',
    appId: '1:318323347329:ios:e938215dfc008b05b66280',
    messagingSenderId: '318323347329',
    projectId: 'smsviewerapp-42d29',
    databaseURL: 'https://smsviewerapp-42d29-default-rtdb.firebaseio.com',
    storageBucket: 'smsviewerapp-42d29.firebasestorage.app',
    iosBundleId: 'com.example.odometerTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn8bSPKhI30hssnoEJ4WL_b7kAsRocpxg',
    appId: '1:318323347329:ios:e938215dfc008b05b66280',
    messagingSenderId: '318323347329',
    projectId: 'smsviewerapp-42d29',
    databaseURL: 'https://smsviewerapp-42d29-default-rtdb.firebaseio.com',
    storageBucket: 'smsviewerapp-42d29.firebasestorage.app',
    iosBundleId: 'com.example.odometerTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASIqFd0jFYo5Wwd8uVxF6q2xSCQFrvC90',
    appId: '1:318323347329:web:2e6d1d6a777c62a9b66280',
    messagingSenderId: '318323347329',
    projectId: 'smsviewerapp-42d29',
    authDomain: 'smsviewerapp-42d29.firebaseapp.com',
    databaseURL: 'https://smsviewerapp-42d29-default-rtdb.firebaseio.com',
    storageBucket: 'smsviewerapp-42d29.firebasestorage.app',
    measurementId: 'G-WTVH29M8FB',
  );
}
